### ISSUE TITLE
Add light gun support

### ISSUE THREAD

**Issue by JoeMatt** [Provenance-Emu/Provenance#933]
### TODO ###
- [ ] Which systems support light gun
- [ ] Touch input controls
- [ ] Determine if cores can smartly give feedback if current ROM is a light gun game
- [ ] Way to toggle lightgun controller mode on / off

**Comment by illando** [comment]
This is the list of systems that supports lightgun mode using mouse emulation in Openemu:

NES:
Fceu 2.2.3

Master System and Genesis:
lr-genesis-plus-gx v. 1.7.4

Don’t know if Medafen can support lightgun emulation for PS1...play Time Crisis on touchscreen could be a dream! :)

**Comment by JoeMatt** [comment]
#2658 replaces this
